[[dettagli-personali]]
= icon:user[] Dettagli Personali

[.text-justify]
Appassionato per l’informatica fin da piccolo quando giocavo con il Commodore 64 di mio fratello; di conseguenza la maggior parte dei miei hobby le si sono sviluppati attorno: dagli approcci alla domotica con l’uso e la programmazione di schede “Arduino” e “Raspberry Pi”, fino alle consolle, i videogiochi e la programmazione, passando per piccoli esperimenti di saldatura.

[caption=]
[cols="1,12"]
[frame=none]
[grid=none]
.Contatti
|===
^| icon:phone[] | {numeroDiTelefonoPersonale}
^| icon:envelope[] | mailto:{emailPersonale}[{emailPersonale},role=email]
|===

[caption=]
[cols="1,12"]
[frame=none]
[grid=none]
.HomePage
|===
^| icon:globe[] | {url-homepage-Personale}[luzzetti.github.io]
|===

[caption=]
[cols="1,12"]
[frame=none]
[grid=none]
.Socials
|===
^| icon:linkedin[] | {url-linkedin-personale}[/in/luzzetti]
^| icon:github[] | {url-github-personale}[github.com/luzzetti]
|===

[caption=]
[cols="1,12"]
[frame=none]
[grid=none]
.Residenza
|===
^| icon:map-marker[] | {uri-residenza-personale}[{residenza-personale}]
|===

