= icon:graduation-cap[] Educazione e Formazione

[[certificazioni-e-nanodegrees]]
== Certificazioni e Corsi

icon:bookmark[] {url-form-devops-fundamentals}[DevOps Fundamentals (PeopleCert)] +

icon:bookmark[] {url-form-liquibase-fundamentals}[Liquibase Fundamentals (Liquibase University)] +

icon:bookmark[] {url-form-javascript-algorithm-and-data-structures}[Javascript Algorithm & Data Structures (FreeCodeCamp)] +

icon:bookmark[] {url-form-oracle-sql-performance-tuning}[Oracle SQL Performance Tuning (Udemy)] +

icon:bookmark[] {url-form-mongodb-M001-certification-verify}[M001: MongoDB Basics (MongoDb University)] +

icon:bookmark[] {url-form-vaadin-14-developer-certification-verify}[Vaadin 14 Developer (Vaadin)] +

icon:bookmark[] {url-form-git_and_github-certification-verify}[Git & GitHub (Udemy)] +

icon:bookmark[] {url-form-spring-and-hibernate-certification-verify}[Spring & Hibernate (Udemy)] +

icon:bookmark[] {url-form-oracle-javaEE7-certification-verify}[Developing Applications for the Java EE 7 Platform (Oracle University)]


[[background-accademico]]
== Background Accademico

Corso di Laurea in Informatica - Classe L-31::
icon:calendar[] `2023 - In Corso` +
icon:university[] {url-universita-pegaso}[{universita-pegaso}] +

Corso di Laurea in Informatica - Classe L-31::
icon:calendar[] `2010 - Non Conseguita` +
icon:university[] {url-universita-la-sapienza}[{universita-la-sapienza}] +
[.small]#Rinuncia agli studi, con 19 esami sostenuti, su un totale di 22# +
[.small]#{url-esami-sostenuti}[Vedi esiti esami]#

Programmatore, Ragioniere e Perito Commerciale::
icon:calendar[] `2003 - 2009` +
icon:university[] {url-paolo-savi}[{paolo-savi}]
