[[personal-details]]
= icon:user[] Personal Details

[.text-justify]
Passionate about computer science since childhood, my interest began with experimenting on a Commodore 64. Over time, I honed my skills in programming, engaging in projects with Arduino and Raspberry Pi.
Now, as a full-time software engineer specialized in Java, I develop robust software solutions, troubleshoot systems, and mentor junior developers. +
In my free time, I enjoy experimenting with new technologies and languages to broaden my knowledge, and I am eager to bring my skills and experience to international projects by working abroad.

[caption=]
[cols="1,12"]
[frame=none]
[grid=none]
.Contatti
|===
^| icon:phone[] | {numeroDiTelefonoPersonale}
^| icon:envelope[] | mailto:{emailPersonale}[{emailPersonale},role=email]
|===

[caption=]
[cols="1,12"]
[frame=none]
[grid=none]
.HomePage
|===
^| icon:globe[] | {url-homepage-Personale}[luzzetti.github.io]
|===

[caption=]
[cols="1,12"]
[frame=none]
[grid=none]
.Socials
|===
^| icon:linkedin[] | {url-linkedin-personale}[/in/luzzetti]
^| icon:github[] | {url-github-personale}[github.com/luzzetti]
|===

[caption=]
[cols="1,12"]
[frame=none]
[grid=none]
.Residenza
|===
^| icon:map-marker[] | {uri-residenza-personale}[{residenza-personale}]
|===

